In [ ]:
import pandas as pd
import numpy as np
dataset = pd.read_csv("TRAIN.csv")
dataset

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday Discount  #Order     Sales  
0             1      Yes       9   7011.84  
1             1      Yes      60  51789.12  
2             1      Yes      42  36868.20  
3             1      Yes      23  19715.16  
4             1      Yes      62  45614.52  
...         ...      ...     ...       ...  
188335        1      Yes      51  37272.00  
188336        1       No      90  54572.64  
188337        1       No      56  31624.56  
188338        1      Yes      70  49162.41  
188339        1       No      47  37977.00  

[188340 rows x 10 columns]

In [42]:
dataset

ID  Store_id Store_Type Location_Type Region_Code        Date  \
0       T1000001         1         S1            L3          R1  2018-01-01   
1       T1000002       253         S4            L2          R1  2018-01-01   
2       T1000003       252         S3            L2          R1  2018-01-01   
3       T1000004       251         S2            L3          R1  2018-01-01   
4       T1000005       250         S2            L3          R4  2018-01-01   
...          ...       ...        ...           ...         ...         ...   
188335  T1188336       149         S2            L3          R2  2019-05-31   
188336  T1188337       153         S4            L2          R1  2019-05-31   
188337  T1188338       154         S1            L3          R2  2019-05-31   
188338  T1188339       155         S3            L1          R2  2019-05-31   
188339  T1188340       152         S2            L1          R1  2019-05-31   

        Holiday Discount  #Order     Sales  
0             1      Yes       9   7011.84  
1             1      Yes      60  51789.12  
2             1      Yes      42  36868.20  
3             1      Yes      23  19715.16  
4             1      Yes      62  45614.52  
...         ...      ...     ...       ...  
188335        1      Yes      51  37272.00  
188336        1       No      90  54572.64  
188337        1       No      56  31624.56  
188338        1      Yes      70  49162.41  
188339        1       No      47  37977.00  

[188340 rows x 10 columns]

In [ ]:
dataset.describe()


Store_id        Holiday         #Order          Sales
count  188340.000000  188340.000000  188340.000000  188340.000000
mean      183.000000       0.131783      68.205692   42784.327982
std       105.366308       0.338256      30.467415   18456.708302
min         1.000000       0.000000       0.000000       0.000000
25%        92.000000       0.000000      48.000000   30426.000000
50%       183.000000       0.000000      63.000000   39678.000000
75%       274.000000       0.000000      82.000000   51909.000000
max       365.000000       1.000000     371.000000  247215.000000

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188340 entries, 0 to 188339
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   ID             188340 non-null  object 
 1   Store_id       188340 non-null  int64  
 2   Store_Type     188340 non-null  object 
 3   Location_Type  188340 non-null  object 
 4   Region_Code    188340 non-null  object 
 5   Date           188340 non-null  object 
 6   Holiday        188340 non-null  int64  
 7   Discount       188340 non-null  object 
 8   #Order         188340 non-null  int64  
 9   Sales          188340 non-null  float64
dtypes: float64(1), int64(3), object(6)
memory usage: 14.4+ MB


In [ ]:
dataset.isnull().sum()

ID               0
Store_id         0
Store_Type       0
Location_Type    0
Region_Code      0
Date             0
Holiday          0
Discount         0
#Order           0
Sales            0
dtype: int64

In [ ]:
import plotly.express as px

In [ ]:
pie1= dataset["Discount"].value_counts()
Discount= pie1.index
Order =pie1.values
fig = px.pie(values=Order, names=Discount)
fig.show()

In [ ]:
fig2= dataset["Location_Type"].value_counts()
location = fig2.index
order = fig2.values
fig = px.pie(values=order, names=location)
fig.show()

In [43]:
fig3 = dataset["Store_Type"].value_counts()
store = fig3.index
order = fig3.values
fig = px.pie(values=order, names=store)
fig.show()

In [ ]:
fig4= dataset["Region_Code"].value_counts()
region = fig4.index
order = fig4.values
fig= px.pie(values=order, names=region)
fig.show()

In [ ]:
dataset["Store_Type"] =dataset["Store_Type"].map({"S1":1,"S2":2,"S3":3,"S4":4})


In [ ]:
fig= dataset["Holiday"].value_counts()
holiday = fig.index
order = fig.values
fig = px.pie(values=order, names=holiday)
fig.show()

In [ ]:
dataset

ID  Store_id  Store_Type Location_Type Region_Code        Date  \
0       T1000001         1           1            L3          R1  2018-01-01   
1       T1000002       253           4            L2          R1  2018-01-01   
2       T1000003       252           3            L2          R1  2018-01-01   
3       T1000004       251           2            L3          R1  2018-01-01   
4       T1000005       250           2            L3          R4  2018-01-01   
...          ...       ...         ...           ...         ...         ...   
188335  T1188336       149           2            L3          R2  2019-05-31   
188336  T1188337       153           4            L2          R1  2019-05-31   
188337  T1188338       154           1            L3          R2  2019-05-31   
188338  T1188339       155           3            L1          R2  2019-05-31   
188339  T1188340       152           2            L1          R1  2019-05-31   

        Holiday Discount  #Order     Sales  
0             1      Yes       9   7011.84  
1             1      Yes      60  51789.12  
2             1      Yes      42  36868.20  
3             1      Yes      23  19715.16  
4             1      Yes      62  45614.52  
...         ...      ...     ...       ...  
188335        1      Yes      51  37272.00  
188336        1       No      90  54572.64  
188337        1       No      56  31624.56  
188338        1      Yes      70  49162.41  
188339        1       No      47  37977.00  

[188340 rows x 10 columns]

In [ ]:
dataset["Location_Type"]=dataset["Location_Type"].map({"L1":1,"L2":2,"L3":3,"L4":4,"L5":5})


In [ ]:
dataset

ID  Store_id  Store_Type  Location_Type Region_Code        Date  \
0       T1000001         1           1              3          R1  2018-01-01   
1       T1000002       253           4              2          R1  2018-01-01   
2       T1000003       252           3              2          R1  2018-01-01   
3       T1000004       251           2              3          R1  2018-01-01   
4       T1000005       250           2              3          R4  2018-01-01   
...          ...       ...         ...            ...         ...         ...   
188335  T1188336       149           2              3          R2  2019-05-31   
188336  T1188337       153           4              2          R1  2019-05-31   
188337  T1188338       154           1              3          R2  2019-05-31   
188338  T1188339       155           3              1          R2  2019-05-31   
188339  T1188340       152           2              1          R1  2019-05-31   

        Holiday Discount  #Order     Sales  
0             1      Yes       9   7011.84  
1             1      Yes      60  51789.12  
2             1      Yes      42  36868.20  
3             1      Yes      23  19715.16  
4             1      Yes      62  45614.52  
...         ...      ...     ...       ...  
188335        1      Yes      51  37272.00  
188336        1       No      90  54572.64  
188337        1       No      56  31624.56  
188338        1      Yes      70  49162.41  
188339        1       No      47  37977.00  

[188340 rows x 10 columns]

In [ ]:
dataset["Region_Code"]=dataset["Region_Code"].map({"R1":1,"R2":2,"R3":3,"R4":4,"R5":5})

In [ ]:
dataset

ID  Store_id  Store_Type  Location_Type  Region_Code  \
0       T1000001         1           1              3            1   
1       T1000002       253           4              2            1   
2       T1000003       252           3              2            1   
3       T1000004       251           2              3            1   
4       T1000005       250           2              3            4   
...          ...       ...         ...            ...          ...   
188335  T1188336       149           2              3            2   
188336  T1188337       153           4              2            1   
188337  T1188338       154           1              3            2   
188338  T1188339       155           3              1            2   
188339  T1188340       152           2              1            1   

              Date  Holiday Discount  #Order     Sales  
0       2018-01-01        1      Yes       9   7011.84  
1       2018-01-01        1      Yes      60  51789.12  
2       2018-01-01        1      Yes      42  36868.20  
3       2018-01-01        1      Yes      23  19715.16  
4       2018-01-01        1      Yes      62  45614.52  
...            ...      ...      ...     ...       ...  
188335  2019-05-31        1      Yes      51  37272.00  
188336  2019-05-31        1       No      90  54572.64  
188337  2019-05-31        1       No      56  31624.56  
188338  2019-05-31        1      Yes      70  49162.41  
188339  2019-05-31        1       No      47  37977.00  

[188340 rows x 10 columns]

In [ ]:
dataset["Discount"]=dataset["Discount"].map({"Yes":1,"No":0})

In [ ]:
dataset

ID  Store_id  Store_Type  Location_Type  Region_Code  \
0       T1000001         1           1              3            1   
1       T1000002       253           4              2            1   
2       T1000003       252           3              2            1   
3       T1000004       251           2              3            1   
4       T1000005       250           2              3            4   
...          ...       ...         ...            ...          ...   
188335  T1188336       149           2              3            2   
188336  T1188337       153           4              2            1   
188337  T1188338       154           1              3            2   
188338  T1188339       155           3              1            2   
188339  T1188340       152           2              1            1   

              Date  Holiday  Discount  #Order     Sales  
0       2018-01-01        1         1       9   7011.84  
1       2018-01-01        1         1      60  51789.12  
2       2018-01-01        1         1      42  36868.20  
3       2018-01-01        1         1      23  19715.16  
4       2018-01-01        1         1      62  45614.52  
...            ...      ...       ...     ...       ...  
188335  2019-05-31        1         1      51  37272.00  
188336  2019-05-31        1         0      90  54572.64  
188337  2019-05-31        1         0      56  31624.56  
188338  2019-05-31        1         1      70  49162.41  
188339  2019-05-31        1         0      47  37977.00  

[188340 rows x 10 columns]

In [ ]:
x= np.array(dataset[["Store_Type","Location_Type","Region_Code","Discount"]])
y= np.array(dataset["#Order"])

In [ ]:
x

array([[1, 3, 1, 1],
       [4, 2, 1, 1],
       [3, 2, 1, 1],
       ...,
       [1, 3, 2, 0],
       [3, 1, 2, 1],
       [2, 1, 1, 0]])

In [ ]:
y

array([ 9, 60, 42, ..., 56, 70, 47])

In [ ]:
# building ml model
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
len(x_train)

150672

In [ ]:
#large dataset so pip install ligthgbm
import lightgbm as ltb
model = ltb.LGBMRegressor()


In [ ]:
model.fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.



[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004389 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 18
[LightGBM] [Info] Number of data points in the train set: 150672, number of used features: 4
[LightGBM] [Info] Start training from score 68.163401


LGBMRegressor()

In [ ]:
y_pred= model.predict(x_test)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.



In [ ]:
y_pred

array([ 49.38300848, 127.88888462,  66.27159031, ...,  44.31657034,
        61.13235067,  82.42387359])

In [ ]:
y_test

array([ 54, 111,  59, ...,  40,  69,  68])

In [ ]:
data= pd.DataFrame(data={"predicted orders": y_pred.flatten()})

In [ ]:
data

predicted orders
0             49.383008
1            127.888885
2             66.271590
3             82.864884
4             54.550167
...                 ...
37663         66.271590
37664         50.959433
37665         44.316570
37666         61.132351
37667         82.423874

[37668 rows x 1 columns]